FROM httpd:2.4-alpine

# Install mod_php dependencies (if needed)
# Note: Apache with mod_php is less common in modern setups
# This Dockerfile sets up Apache as a reverse proxy to PHP-FPM

RUN apk add --no-cache \
    apache2-proxy \
    apache2-utils

# Copy Apache configuration
COPY docker/apache/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY docker/apache/vhost.conf /usr/local/apache2/conf/extra/vhost.conf

# Enable required modules
RUN sed -i 's/#LoadModule proxy_module/LoadModule proxy_module/' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/#LoadModule proxy_fcgi_module/LoadModule proxy_fcgi_module/' /usr/local/apache2/conf/httpd.conf

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]

