<?php
/**
 * Comprehensive ClickHouse Data Validation Test
 * 
 * This script validates that all types of data (spans, traces, SQL, HTTP, etc.)
 * are properly stored in ClickHouse after being generated by the OPA extension.
 * 
 * Usage: php test_clickhouse_validation.php
 */

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\HttpFoundation\Request;
use App\Kernel;

echo "=== ClickHouse Data Validation Test ===\n\n";

// Configuration
$CLICKHOUSE_URL = 'http://clickhouse:8123';
$WAIT_TIME = 15; // Wait time for agent to process spans (seconds)

$tests_passed = 0;
$tests_failed = 0;
$errors = [];

// Helper function to query ClickHouse
function queryClickHouse($url, $query) {
    $ch = curl_init($url);
    if (!$ch) {
        return ['error' => 'Failed to initialize cURL', 'data' => null];
    }
    
    curl_setopt_array($ch, [
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $query,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 10,
    ]);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $error = curl_error($ch);
    curl_close($ch);
    
    if ($error) {
        return ['error' => $error, 'data' => null, 'http_code' => $httpCode];
    }
    
    if ($httpCode !== 200) {
        return ['error' => "HTTP $httpCode: " . substr($response, 0, 200), 'data' => null, 'http_code' => $httpCode];
    }
    
    // Parse JSONEachRow format
    $data = [];
    $lines = explode("\n", trim($response));
    foreach ($lines as $line) {
        if (empty(trim($line))) continue;
        $row = json_decode($line, true);
        if ($row) {
            $data[] = $row;
        }
    }
    
    return ['error' => null, 'data' => $data, 'http_code' => $httpCode];
}

// Test 1: Check ClickHouse connectivity
echo "Test 1: Checking ClickHouse connectivity...\n";
$result = queryClickHouse($CLICKHOUSE_URL, "SELECT 1 as test FORMAT JSONEachRow");
if ($result['error']) {
    echo "   ✗ FAILED: Cannot connect to ClickHouse: {$result['error']}\n";
    $errors[] = "ClickHouse connectivity: {$result['error']}";
    $tests_failed++;
    exit(1);
} else {
    echo "   ✓ ClickHouse is accessible\n";
    $tests_passed++;
}

// Test 2: Check if required tables exist
echo "\nTest 2: Checking if required tables exist...\n";
$required_tables = ['spans_full', 'spans_min'];
$optional_tables = ['traces_full', 'traces_min'];

foreach ($required_tables as $table) {
    $result = queryClickHouse($CLICKHOUSE_URL, "EXISTS TABLE opa.$table FORMAT JSONEachRow");
    if ($result['error']) {
        echo "   ✗ FAILED: Error checking table $table: {$result['error']}\n";
        $errors[] = "Table $table check: {$result['error']}";
        $tests_failed++;
    } elseif (empty($result['data']) || !isset($result['data'][0]['result']) || $result['data'][0]['result'] != 1) {
        echo "   ✗ FAILED: Table opa.$table does not exist\n";
        $errors[] = "Table opa.$table does not exist";
        $tests_failed++;
    } else {
        echo "   ✓ Table opa.$table exists\n";
        $tests_passed++;
    }
}

foreach ($optional_tables as $table) {
    $result = queryClickHouse($CLICKHOUSE_URL, "EXISTS TABLE opa.$table FORMAT JSONEachRow");
    if ($result['error'] || empty($result['data']) || !isset($result['data'][0]['result']) || $result['data'][0]['result'] != 1) {
        echo "   ⚠ Table opa.$table does not exist (optional)\n";
    } else {
        echo "   ✓ Table opa.$table exists\n";
        $tests_passed++;
    }
}

// Test 3: Generate test data via HTTP requests
echo "\nTest 3: Generating test data...\n";
$kernel = new Kernel('dev', true);
$kernel->boot();

$test_trace_id = null;
$test_span_id = null;

// Make a request that will generate spans, SQL, HTTP data
$request = Request::create('/api/test/comprehensive', 'GET');
$response = $kernel->handle($request);
$kernel->terminate($request, $response);

echo "   ✓ Generated test request (status: {$response->getStatusCode()})\n";
$tests_passed++;

// Test 4: Wait for agent to process
echo "\nTest 4: Waiting {$WAIT_TIME} seconds for agent to process spans...\n";
sleep($WAIT_TIME);
echo "   ✓ Wait complete\n";
$tests_passed++;

// Test 5: Check for recent spans in spans_full
echo "\nTest 5: Checking for recent spans in spans_full...\n";
$query = "
SELECT 
    trace_id,
    span_id,
    name,
    service,
    start_ts,
    duration_ms,
    parent_id
FROM opa.spans_full 
WHERE start_ts >= now() - INTERVAL 10 MINUTE
ORDER BY start_ts DESC 
LIMIT 20
FORMAT JSONEachRow
";

$result = queryClickHouse($CLICKHOUSE_URL, $query);
if ($result['error']) {
    echo "   ✗ FAILED: Error querying spans_full: {$result['error']}\n";
    $errors[] = "spans_full query: {$result['error']}";
    $tests_failed++;
} elseif (empty($result['data'])) {
    echo "   ✗ FAILED: No spans found in the last 10 minutes\n";
    $errors[] = "No spans found in spans_full";
    $tests_failed++;
} else {
    $span_count = count($result['data']);
    echo "   ✓ Found $span_count recent span(s)\n";
    
    // Display first few spans
    $display_count = min(3, $span_count);
    for ($i = 0; $i < $display_count; $i++) {
        $span = $result['data'][$i];
        echo "      - {$span['name']} (trace: " . substr($span['trace_id'], 0, 16) . "...)\n";
    }
    
    // Store first trace_id for further tests
    if (!empty($result['data'])) {
        $test_trace_id = $result['data'][0]['trace_id'];
        $test_span_id = $result['data'][0]['span_id'];
    }
    
    $tests_passed++;
}

// Test 6: Check for traces (optional table)
echo "\nTest 6: Checking for traces...\n";
$query = "
SELECT 
    trace_id,
    span_count,
    start_ts,
    duration_ms,
    service
FROM opa.traces_full 
WHERE start_ts >= now() - INTERVAL 10 MINUTE
ORDER BY start_ts DESC 
LIMIT 10
FORMAT JSONEachRow
";

$result = queryClickHouse($CLICKHOUSE_URL, $query);
if ($result['error'] && strpos($result['error'], "doesn't exist") === false) {
    echo "   ✗ FAILED: Error querying traces_full: {$result['error']}\n";
    $errors[] = "traces_full query: {$result['error']}";
    $tests_failed++;
} elseif ($result['error'] && strpos($result['error'], "doesn't exist") !== false) {
    echo "   ⚠ WARNING: traces_full table does not exist (optional table)\n";
} elseif (empty($result['data'])) {
    echo "   ⚠ WARNING: No traces found (this might be normal if traces_full table is not populated)\n";
} else {
    $trace_count = count($result['data']);
    echo "   ✓ Found $trace_count recent trace(s)\n";
    $tests_passed++;
}

// Test 7: Check for SQL queries in spans_full
echo "\nTest 7: Checking for SQL queries in spans...\n";
$query = "
SELECT 
    trace_id,
    span_id,
    name,
    sql
FROM opa.spans_full 
WHERE start_ts >= now() - INTERVAL 10 MINUTE
  AND sql != ''
  AND sql IS NOT NULL
ORDER BY start_ts DESC 
LIMIT 10
FORMAT JSONEachRow
";

$result = queryClickHouse($CLICKHOUSE_URL, $query);
if ($result['error']) {
    echo "   ✗ FAILED: Error querying SQL in spans: {$result['error']}\n";
    $errors[] = "SQL query in spans: {$result['error']}";
    $tests_failed++;
} elseif (empty($result['data'])) {
    echo "   ⚠ WARNING: No SQL queries found in spans (this might be normal if no SQL was executed)\n";
} else {
    $sql_count = count($result['data']);
    echo "   ✓ Found $sql_count span(s) with SQL queries\n";
    
    // Display first query
    if (!empty($result['data'])) {
        $span = $result['data'][0];
        $sql_json = json_decode($span['sql'], true);
        if ($sql_json && isset($sql_json[0]['query'])) {
            $query_preview = substr($sql_json[0]['query'], 0, 60);
            echo "      - $query_preview...\n";
        }
    }
    
    $tests_passed++;
}

// Test 8: Check for HTTP requests in spans_full
echo "\nTest 8: Checking for HTTP requests in spans...\n";
$query = "
SELECT 
    trace_id,
    span_id,
    name,
    http
FROM opa.spans_full 
WHERE start_ts >= now() - INTERVAL 10 MINUTE
  AND http != ''
  AND http IS NOT NULL
ORDER BY start_ts DESC 
LIMIT 10
FORMAT JSONEachRow
";

$result = queryClickHouse($CLICKHOUSE_URL, $query);
if ($result['error']) {
    echo "   ✗ FAILED: Error querying HTTP in spans: {$result['error']}\n";
    $errors[] = "HTTP query in spans: {$result['error']}";
    $tests_failed++;
} elseif (empty($result['data'])) {
    echo "   ⚠ WARNING: No HTTP requests found in spans (this might be normal if no HTTP requests were made)\n";
} else {
    $http_count = count($result['data']);
    echo "   ✓ Found $http_count span(s) with HTTP requests\n";
    
    // Display first request
    if (!empty($result['data'])) {
        $span = $result['data'][0];
        $http_json = json_decode($span['http'], true);
        if ($http_json && isset($http_json[0]['method']) && isset($http_json[0]['url'])) {
            echo "      - {$http_json[0]['method']} {$http_json[0]['url']}\n";
        }
    }
    
    $tests_passed++;
}

// Test 9: Validate span data structure
if ($test_trace_id) {
    echo "\nTest 9: Validating span data structure for trace $test_trace_id...\n";
    $query = "
    SELECT 
        trace_id,
        span_id,
        name,
        service,
        start_ts,
        duration_ms,
        parent_id,
        tags,
        net,
        sql,
        http
    FROM opa.spans_full 
    WHERE trace_id = '" . addslashes($test_trace_id) . "'
    ORDER BY start_ts
    LIMIT 5
    FORMAT JSONEachRow
    ";
    
    $result = queryClickHouse($CLICKHOUSE_URL, $query);
    if ($result['error']) {
        echo "   ✗ FAILED: Error querying span details: {$result['error']}\n";
        $errors[] = "Span details query: {$result['error']}";
        $tests_failed++;
    } elseif (empty($result['data'])) {
        echo "   ✗ FAILED: No spans found for trace $test_trace_id\n";
        $errors[] = "No spans found for trace";
        $tests_failed++;
    } else {
        $span = $result['data'][0];
        $required_fields = ['trace_id', 'span_id', 'name', 'service', 'start_ts', 'duration_ms'];
        $missing_fields = [];
        
        foreach ($required_fields as $field) {
            if (!isset($span[$field])) {
                $missing_fields[] = $field;
            }
        }
        
        if (!empty($missing_fields)) {
            echo "   ✗ FAILED: Missing required fields: " . implode(', ', $missing_fields) . "\n";
            $errors[] = "Missing span fields: " . implode(', ', $missing_fields);
            $tests_failed++;
        } else {
            echo "   ✓ Span data structure is valid\n";
            echo "      - Trace ID: {$span['trace_id']}\n";
            echo "      - Span ID: {$span['span_id']}\n";
            echo "      - Name: {$span['name']}\n";
            echo "      - Service: {$span['service']}\n";
            echo "      - Duration: {$span['duration_ms']} ms\n";
            $tests_passed++;
        }
    }
}

// Test 10: Check agent health
echo "\nTest 10: Checking agent health...\n";
$ch = curl_init('http://agent:8080/api/health');
if ($ch) {
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 5);
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($httpCode === 200) {
        $health = json_decode($response, true);
        if ($health && isset($health['status']) && $health['status'] === 'ok') {
            echo "   ✓ Agent is healthy\n";
            $tests_passed++;
        } else {
            echo "   ⚠ WARNING: Agent health check returned unexpected response\n";
        }
    } else {
        echo "   ⚠ WARNING: Agent health check returned HTTP $httpCode\n";
    }
} else {
    echo "   ⚠ WARNING: Could not check agent health (curl_init failed)\n";
}

// Summary
echo "\n" . str_repeat("=", 80) . "\n";
echo "=== Test Summary ===\n";
echo "Tests passed: $tests_passed\n";
echo "Tests failed: $tests_failed\n\n";

if ($tests_failed > 0) {
    echo "ERRORS:\n";
    foreach ($errors as $error) {
        echo "  - $error\n";
    }
    echo "\n";
    exit(1);
} else {
    echo "✓ All tests passed! Data is successfully reaching ClickHouse.\n";
    echo "\nValidation complete:\n";
    echo "  - ClickHouse connectivity: ✓\n";
    echo "  - Required tables exist: ✓\n";
    echo "  - Spans are being stored: ✓\n";
    echo "  - Data structure is valid: ✓\n";
    exit(0);
}

